#%RAML 0.8
title: WN_SMART_METER_API
version: "1.0"
baseUri: "https://api.wstw.at/gateway/WN_SMART_METER_API/1.0"
protocols: [HTTPS]
mediaType: application/json
schemas: 
    - 
        Geraet: '{"required":["geraetenummer","equipmentnummer"],"type":"object","properties":{"equipmentnummer":{"type":"string"},"geraetenummer":{"type":"string"}}}'
        Messwert: '{"required":["zeitVon","qualitaet","messwert","zeitBis"],"type":"object","properties":{"messwert":{"type":"integer","format":"int64"},"qualitaet":{"type":"string"},"zeitBis":{"type":"string"},"zeitVon":{"type":"string"}}}'
        zaehlpunktezaehlpunktmesswerte_GET_response: '{"required":["zaehlwerke","zaehlpunkt"],"type":"object","properties":{"zaehlpunkt":{"type":"string"},"zaehlwerke":{"type":"array","items":{"$ref":"#/definitions/ZaehlwerkMesswerte"}}}}'
        ZaehlwerkMesswerte: '{"required":["einheit","obisCode","messwerte"],"type":"object","properties":{"einheit":{"type":"string"},"messwerte":{"type":"array","items":{"$ref":"#/definitions/Messwert"}},"obisCode":{"type":"string"}}}'
        Verbrauchsstelle: '{"required":["ort","postleitzahl","hausnummer2","strasse","tuernummer","haus","hausnummer1","stockwerk","land","strasseZusatz"],"type":"object","properties":{"haus":{"type":"string"},"hausnummer1":{"type":"string"},"hausnummer2":{"type":"string"},"land":{"type":"string"},"ort":{"type":"string"},"postleitzahl":{"type":"string"},"stockwerk":{"type":"string"},"strasse":{"type":"string"},"strasseZusatz":{"type":"string"},"tuernummer":{"type":"string"}}}'
        zaehlpunkte_GET_response: '{"type":"object","properties":{"type":"array","items":{"$ref":"#/definitions/Zaehlpunkt"}}}'
        ZaehlpunktMesswerte: '{"required":["zaehlwerke","zaehlpunkt"],"type":"object","properties":{"zaehlpunkt":{"type":"string"},"zaehlwerke":{"type":"array","items":{"$ref":"#/definitions/ZaehlwerkMesswerte"}}}}'
        zaehlpunktemesswerte_GET_response: '{"required":["$rootArray"],"type":"object","properties":{"type":"array","items":{"$ref":"#/definitions/ZaehlpunktMesswerte"}}}'
        Anlage: '{"required":["anlage","sparte","typ"],"type":"object","properties":{"anlage":{"type":"string"},"sparte":{"type":"string"},"typ":{"type":"string"}}}'
        Zaehlpunkt: '{"required":["zaehlpunktnummer","verbrauchsstelle","anlage","geraet","zaehlpunktname","idex"],"type":"object","properties":{"anlage":{"$ref":"#/definitions/Anlage"},"geraet":{"$ref":"#/definitions/Geraet"},"idex":{"$ref":"#/definitions/Idex"},"verbrauchsstelle":{"$ref":"#/definitions/Verbrauchsstelle"},"zaehlpunktname":{"type":"string"},"zaehlpunktnummer":{"type":"string"}}}'
        Idex: '{"required":["granularity","displayLocked","customerInterface"],"type":"object","properties":{"customerInterface":{"type":"string"},"displayLocked":{"type":"boolean"},"granularity":{"type":"string"}}}'
        zaehlpunktezaehlpunkt_GET_response: '{"type":"object","properties":{"anlage":{"$ref":"#/definitions/Anlage"},"geraet":{"$ref":"#/definitions/Geraet"},"idex":{"$ref":"#/definitions/Idex"},"verbrauchsstelle":{"$ref":"#/definitions/Verbrauchsstelle"},"zaehlpunktname":{"type":"string"},"zaehlpunktnummer":{"type":"string"}}}'
securitySchemes: 
    - 
        oAuth2Token: 
            type: OAuth 2.0
            settings: 
                accessTokenUri: "https://api.wstw.at/invoke/pub.apigateway.oauth2/getAccessToken"
                authorizationGrants: [credentials]
                scopes: [ecad3cdc-3db1-11ea-94c8-b00481db114b]
        apiKey: 
            type: x-apiKey
            describedBy: 
                headers: 
                    Authorization: 
                        type: string
                        required: false
                        repeat: false
securedBy: 
    - 
        apiKey
    - 
        oAuth2Token
/zaehlpunkte: 
    displayName: /zaehlpunkte
    get: 
        queryParameters: 
            webProfileId: 
                type: string
                required: false
                repeat: false
            zaehlpunkt: 
                type: string
                required: false
                repeat: true
            resultType: 
                type: string
                required: false
                repeat: false
        body: 
            multipart/form-data: 
                formParameters: 
                    oauthToken: 
                        type: string
                        required: false
                        repeat: false
        responses: 
            "200": 
                description: Successful
                body: 
                    application/json: 
                        schema: zaehlpunkte_GET_response
            "400": 
                description: Bad Request
            "401": 
                description: Access Denied
            "500": 
                description: Internal Server Error
            "403": 
                description: Forbidden
            "404": 
                description: Not found
    /messwerte: 
        displayName: /zaehlpunkte/messwerte
        get: 
            queryParameters: 
                webProfileId: 
                    type: string
                    required: false
                    repeat: false
                datumVon: 
                    type: string
                    required: true
                    repeat: false
                zaehlpunkt: 
                    type: string
                    required: false
                    repeat: true
                datumBis: 
                    type: string
                    required: true
                    repeat: false
                wertetyp: 
                    type: string
                    required: true
                    repeat: false
            body: 
                multipart/form-data: 
                    formParameters: 
                        oauthToken: 
                            type: string
                            required: false
                            repeat: false
            responses: 
                "200": 
                    description: Successful
                    body: 
                        application/json: 
                            schema: zaehlpunktemesswerte_GET_response
                "400": 
                    description: Bad Request
                "401": 
                    description: Access Denied
                "500": 
                    description: Internal Server Error
                "403": 
                    description: Forbidden
                "404": 
                    description: Not found
    /{zaehlpunkt}: 
        displayName: /zaehlpunkte/{zaehlpunkt}
        get: 
            queryParameters: 
                webProfileId: 
                    type: string
                    required: false
                    repeat: false
            body: 
                multipart/form-data: 
                    formParameters: 
                        oauthToken: 
                            type: string
                            required: false
                            repeat: false
            responses: 
                "200": 
                    description: Successful
                    body: 
                        application/json: 
                            schema: zaehlpunktezaehlpunkt_GET_response
                "400": 
                    description: Bad Request
                "401": 
                    description: Access Denied
                "500": 
                    description: Internal Server Error
                "403": 
                    description: Forbidden
                "404": 
                    description: Not found
            baseUriParameters: 
                zaehlpunkt: 
                    type: string
                    required: true
                    repeat: false
        /messwerte: 
            displayName: /zaehlpunkte/{zaehlpunkt}/messwerte
            get: 
                queryParameters: 
                    webProfileId: 
                        type: string
                        required: false
                        repeat: false
                    datumVon: 
                        type: string
                        required: true
                        repeat: false
                    datumBis: 
                        type: string
                        required: true
                        repeat: false
                    wertetyp: 
                        type: string
                        required: true
                        repeat: false
                body: 
                    multipart/form-data: 
                        formParameters: 
                            oauthToken: 
                                type: string
                                required: false
                                repeat: false
                responses: 
                    "200": 
                        description: Successful
                        body: 
                            application/json: 
                                schema: zaehlpunktezaehlpunktmesswerte_GET_response
                    "400": 
                        description: Bad Request
                    "401": 
                        description: Access Denied
                    "500": 
                        description: Internal Server Error
                    "403": 
                        description: Forbidden
                    "404": 
                        description: Not found
                baseUriParameters: 
                    zaehlpunkt: 
                        type: string
                        required: true
                        repeat: false
documentation: 
    - 
        title: API Description
        content: |
            Diese API ermöglicht Kunden, die sich zusätzlich mit OAUTH2 Token authentizieren, den Bezug von Anlagedaten und Verbauchswerten.
            Zur Verfügung stehen sowohl allgemeine Aufrufe nur mit der Geschäftspartnernummer als auch gezielte zählpunktscharfe Anfragen.
    - 
        title: License
        content: Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)
    - 
        title: License URL
        content: "https://creativecommons.org/licenses/by-nc-nd/4.0/"
